### ISSUE TITLE
getJwks.getPublicKey always returns an HTTP 404 Not Found error

### ISSUE THREAD

**Issue by Sjoerd82** [nearform/get-jwks#275]
No matter which `domain` I provide, and regardless of `providerDiscovery` being true or false, I always get a 404 back from `getJwks.getPublicKey()`.

The JWT bearer token arrives nicely, and is correctly decoded. The `iss` contains the Keycloak realm, and also the `kid` and `alg` are correctly decoded. The JWKS is located at https://auth.example.com/realms/xyz/protocol/openid-connect/certs. (real domain redacted for privacy). This is a Keycloak v24 instance, which otherwise works fine.

Still I get errors indicating a 404. The given `domain` URL's are all available without issue.
```
"type":"GetJwksError",
"message":"JWKS request failed",
"stack":"GetJwksError: JWKS request failed
at retrieveJwk (D:\\Dev\\NodeJs\\hercules\\node_modules\\.pnpm\\get-jwks@9.0.1\\node_modules\\get-jwks\\src\\get-jwks.js:118:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.getPublicKey (D:\\Dev\\NodeJs\\hercules\\node_modules\\.pnpm\\get-jwks@9.0.1\\node_modules\\get-jwks\\src\\get-jwks.js:63:21)",
"name":"GetJwksError",
"code":"JWKS_REQUEST_FAILED",
"response":{"size":0,"timeout":5000},"body":{"error":"HTTP 404 Not Found","error_description":"For more on this error consult the server log at the debug level."}},"msg":"JWKS request failed"}
```

```ts
'use strict'

import fs from "node:fs"
import cors from '@fastify/cors'
import https from 'node:https'

const fastify = require('fastify')({
    logger: true,
    exposeHeadRoutes: true,
    http2: true,
    https: {
        cert: fs.readFileSync('localhost.pem', 'utf8'),
        key: fs.readFileSync('localhost-key.pem', 'utf8'),
    },
})
const fjwt = require('@fastify/jwt')
const buildGetJwks = require('get-jwks')
const getJwks = buildGetJwks({
  providerDiscovery: false,
  //agent: new https.Agent({
  //  keepAlive: true,
  //}),
})

fastify.register(cors, {
    origin: '*',
    methods: ["GET"]
})

fastify.register(fjwt, {
  decode: { complete: true },
  secret: (request, token) => {
    const { header: { kid, alg }, payload: { iss } } = token
    //console.log(iss) // https://auth.example.com/realms/xyz
    //console.log(kid) // 80lOsd...
    //console.log(alg) // RS256
    return getJwks.getPublicKey({
      //domain: 'https://auth.example.com/realms/xyz', // JWKS request failed (404), both with providerDiscovery true and false
      //domain: 'https://auth.example.com/realms/xyz/.well-known/openid-configuration', // JWKS request failed (404)
      domain: 'https://auth.example.com/realms/xyz/protocol/openid-connect/certs', // JWKS request failed (404)
      kid, alg
    })
  }
})

fastify.addHook('onRequest', async (request, reply) => {
  try {
    await request.jwtVerify()
  } catch (err) {
    reply.send(err)
  }
})

fastify.get('/secret', (req, reply) => {
  reply.send({authenticated: true})
})

fastify.listen({port: 3113}, (err) => {
  if (err) {
    fastify.log.error(err.message)
    process.exit(1)
  }
})
```

Complete errorlog:
```
{"level":30,"time":1710525332198,"pid":36208,"hostname":"Makemake","msg":"Server listening at https://[::1]:3113"}
{"level":30,"time":1710525332201,"pid":36208,"hostname":"Makemake","msg":"Server listening at https://127.0.0.1:3113"}
{"level":30,"time":1710525339601,"pid":36208,"hostname":"Makemake","reqId":"req-1","req":{"method":"OPTIONS","url":"/secret","hostname":"localhost:3113","remoteAddress":"::1","remotePort":18791},"msg":"incoming request"}
{"level":30,"time":1710525339605,"pid":36208,"hostname":"Makemake","reqId":"req-1","res":{"statusCode":204},"responseTime":3.435800075531006,"msg":"request completed"}
{"level":30,"time":1710525339606,"pid":36208,"hostname":"Makemake","reqId":"req-2","req":{"method":"GET","url":"/secret","hostname":"localhost:3113","remoteAddress":"::1","remotePort":18791},"msg":"incoming request"}
{"level":50,"time":1710525339632,"pid":36208,"hostname":"Makemake","reqId":"req-2","req":{"method":"GET","url":"/secret","hostname":"localhost:3113","remoteAddress":"::1","remotePort":18791},"res":{"statusCode":500},"err":{"type":"GetJwksError","message":"JWKS request failed","stack":"GetJwksError: JWKS request failed\n    at retrieveJwk (D:\\Dev\\NodeJs\\hercules\\node_modules\\.pnpm\\get-jwks@9.0.1\\node_modules\\get-jwks\\src\\get-jwks.js:118:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.getPublicKey (D:\\Dev\\NodeJs\\hercules\\node_modules\\.pnpm\\get-jwks@9.0.1\\node_modules\\get-jwks\\src\\get-jwks.js:63:21)","name":"GetJwksError","code":"JWKS_REQUEST_FAILED","response":{"size":0,"timeout":5000},"body":{"error":"HTTP 404 Not Found","error_description":"For more on this error consult the server log at the debug level."}},"msg":"JWKS request failed"}
{"level":30,"time":1710525339634,"pid":36208,"hostname":"Makemake","reqId":"req-2","res":{"statusCode":500},"responseTime":27.520400047302246,"msg":"request completed"}
```

**Comment by Sjoerd82** [comment]
Found the solution. The `jwksPath` property was missing, and must be a relative path to whatever is in `iss`. For Keycloak (at least v24), this is:
```ts
const getJwks = buildGetJwks({
  providerDiscovery: false,
  jwksPath: '/protocol/openid-connect/certs',
})
```
in combination with:

```
fastify.register(fjwt, {
  decode: { complete: true },
  secret: (request, token) => {
    const { header: { kid, alg }, payload: { iss } } = token
    return getJwks.getPublicKey({
      kid, alg, domain: iss
    })
  }
})
```

Works perfectly!
